/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "matte-black": "#121316",
        "background": "#121316",
        "surface": "#18191E",
        "onyx-surface": "#1E2026",
        "surface-dim": "#121316",
        "surface-bright": "#2A2C34",
        "surface-container": "#18191E",
        "surface-container-low": "#15161A",
        "surface-container-high": "#22242C",
        "surface-container-highest": "#2D303A",
        "surface-container-lowest": "#0D0E10",
        "surface-variant": "#2D303A",
        "rose-gold": "#D98A92",
        "rose-mauve": "#B56571",
        "rose-light": "#F0B8BE",
        "rose-dark": "#8A434E",
        "taupe-muted": "#9E8286",
        "primary": "#D98A92",
        "primary-container": "#B56571",
        "on-primary-container": "#FFFFFF",
        "primary-fixed": "#FDE8EA",
        "primary-fixed-dim": "#F0B8BE",
        "on-primary": "#121316",
        "secondary": "#C8C6C5",
        "secondary-container": "#3A3C44",
        "secondary-fixed": "#E5E2E1",
        "on-background": "#EAE0E1",
        "on-surface": "#EAE0E1",
        "on-surface-variant": "#D0BFC2",
        "outline": "#9E8286",
        "outline-variant": "#4A3D40",
        "tertiary": "#98D4A8",
        "tertiary-container": "#649D75",
        "tertiary-fixed": "#B4F1C3",
        "error": "#FFB4AB",
        "error-container": "#93000A"
      },
      fontFamily: {
        "sans": ["'Plus Jakarta Sans'", "system-ui", "-apple-system", "sans-serif"],
        "serif": ["'Playfair Display'", "'Cormorant Garamond'", "Georgia", "serif"],
        "display": ["'Cormorant Garamond'", "'Playfair Display'", "serif"],
        "mono": ["'Space Grotesk'", "monospace"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "display-lg": ["'Cormorant Garamond'", "'Playfair Display'", "serif"],
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "container-max": "1440px",
        "base": "8px"
      }
    },
  },
  plugins: [],
}
